### ISSUE TITLE
Support for XMLDocument as well as document?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/wicked-good-xpath#7] opened 2015-04-01 19:50 UTC
```
My applications get XML documents from HTTPRequest.responseXML and DOMParser.

How difficult is it to extend your solution so that your solution for document 
also works on these other objects?

```

Original issue reported on code.google.com by `martinwb...@yorkdevres.co.uk` on 25 Mar 2013 at 8:41

**Comment by dlwhiteman** [comment] 2015-07-08 19:42
Here is what I'm trying to do:

```javascript
var parser = new DOMParser();
var document = parser.parseFromString(xml, "application/xml");
var result = document.evaluate(xpath, document, null, XPathResult.ANY_TYPE, null);
```

If wicked good path cannot be used to extend the document object obtained using this approach, is there an alternative approach recommended for use in IE11?  The above code works great in Safari, Firefox, and Chrome.  Thanks in advance!

**Comment by dlwhiteman** [comment] 2015-07-13 22:44
I believe the Edge browser in Windows 10 implements and executes the evaluate() function correctly for XMLDocument.  Therefore, I am basically just interested in using wicked-good-xpath in this scenario on IE11.

**Comment by dlwhiteman** [comment] 2015-07-20 15:19
Can the priority be changed from medium to high on this one?  This is a really big issue for us.  Is there a human that is watching this issue?

**Comment by progressnerd** [comment] 2015-07-21 09:23
@dlwhiteman Can you use IE's selectNode/selectNodes method that is available on XML documents instead?

**Comment by nedjs** [comment] 2015-09-06 23:56
@dlwhiteman I was able to get this working by "tricking" the `wgxpath.install` method to install it onto the document.

```javascript
var parser = new DOMParser();
var document = parser.parseFromString(xml, "application/xml");
wgxpath.install({'document':document});
var result = document.evaluate(xpath, document, null, XPathResult.ANY_TYPE, null);
```

**Comment by Datamancer1110** [comment] 2015-09-23 17:46
Can confirm @nedjs workaround. To clarify:
I still call `wgxpath.install()` as part of my init.
I make an AJAX requests sort of like:

```javascript
$.ajax({
   url: "https://wherever.com",
   type: "GET"
}).done(function(data, textStatus, jqXHR) {
   if (data != undefined && data != null && data != "") {
      wgxpath.install({'document':data});
      //At this point, "data", which is a XMLDocument, has the evaluate function. success!
      successCallback(data);
   }
});
```

**Comment by bedney** [comment] 2015-11-12 20:33
@progressnerd - No, it's not possible to use IE selectNode/selectNodes API on XML Documents created using `new DOMParser()`. These methods are only available to XML Documents created using the old ActiveX creation mechanism (hence MS's need to move to wgxpath for Edge, since ActiveX isn't supported on that platform).

Also, would it be possible to get a new build with the outstanding PRs incorporated? Thanks.

As an aside, we all know that Microsoft is using wgxpath in Edge as it's "XPath solution"... does anyone know if they're contributing bug fixes back to this repo? Is this the "official" repo for wgxpath coming from the old Google Code?

Sorry in advance for all of the questions ;-).

**Comment by Dominator008** [comment] 2016-02-17 08:55
@bedney
1. I've released a new version that incorporates the PRs from @nedjs at: https://github.com/google/wicked-good-xpath/releases/download/1.2/wgxpath.install.js

2. I haven't seen any contributions from Microsoft yet.

3. Yes, this is the official repository for Wicked Good XPath now that Google Code has retired.

**Comment by bedney** [comment] 2016-02-17 21:06
@Dominator008 -

Thanks for doing this release and answering my questions! And thanks to @nedjs for the PRs. Now that we don't have to fuss with configuring the Closure Tools because of this update, I hope to put in a few PRs for some issues I found.

**Comment by Dominator008** [comment] 2016-02-17 23:24
@bedney Thanks, PRs welcome :)

**Comment by progressnerd** [comment] 2016-03-31 16:38
I think I like this idea of installing it on Document.prototype, if it's available.

**Comment by Dominator008** [comment] 2016-03-31 17:07
@ScottFreeCode Would you like to make a pull request :)?

**Comment by Dominator008** [comment] 2016-04-01 09:29
I will mark this as closed by https://github.com/google/wicked-good-xpath/commit/209ca23f8cc0038f6aecdd223d50bf966c573a5e for now.

**Closed by Dominator008** 2016-04-01 09:29 UTC
Labels: auto-migrated, Priority-Medium, Type-Enhancement

**Comment by ScottFreeCode** [comment] 2016-04-05 04:26
Awesome, thanks!

Yeah, I was trying to build it and properly test that it works as intended, and got a bit sidetracked trying to figure out the test-suite in general. Which I never quite did, actually -- I can see fairly easily how tests are supposed to be written, but I can't seem to figure out how to run them. (They seem to be trying to pull in the Closure JS through a path that doesn't exist? But I guess I should probably ask about that at the other open issue.)

Regarding automatic installation, I'm mostly thinking of trying to minimize the difference between using the library and using the browser-supplied functions -- ideally, beyond getting the library to provide the XPath implementation in the first place, code using the XPath functions wouldn't need to be changed at all to pick up the library's implementation in browsers that lack one. Right now it's relatively simple to do that just by having a script tag containing nothing but the call to `install` after the script tag that includes the WGX Javascript file via its `src`. (Well, bar needing to figure out whether to override the browser's implementation, anyway -- I haven't got there yet, so maybe my perspective on the matter is skewed.) But that feels like an odd bit of boilerplate glue to me: if I always have that second script with that same call when using WGX, it almost seems like it would be equivalent in most cases (but marginally simpler on the usage end) to just have it rolled into just the library include. That's just a first impression, though; I'm a fan of explicit over implicit in general, so I'll have to chew that aspect over.

**Comment by Dominator008** [comment] 2016-04-05 19:47
@ScottFreeCode Yeah I haven't got time to setup running the tests. Internally at Google, they are run with Bazel with rules similar to those in https://github.com/bazelbuild/rules_closure.

**Comment by ScottFreeCode** [comment] 2016-04-07 12:35
Would it be worthwhile to add a test (disabled for IE pre 9 like the other XHTML test) for using evaluate on documents generated by DOMParser as "application/xml" after installing it on the main window? I think I can actually do that now.

**Comment by ScottFreeCode** [comment] 2016-04-27 22:33
Followup to my own comments: as regards automatic install, I've since discovered that an AMD loader's "shim config" can handle this very nicely:
```js
require.config({
  packages:[ // This is just configuration to find the packages if installed via "npm".
    {
      name: "wicked-good-xpath",
      location: "node_modules/wicked-good-xpath/dist",
      main: "wgxpath.install"
    },
    { // The domReady module is optional, but handy in any project that uses elements in the document -- and what else is document.evaluate for?
      name: "domReady",
      location: "node_modules/requirejs-domready",
      main: "domReady"
    }
  ],
  shim: { // * * * This is the important part!! * * *
    "wicked-good-xpath/wgxpath.install": {
      exports: "wgxpath",
      init: function() { wgxpath.install() }
    }
  },
  map: { // Why type out "wicked-good-xpath" everywhere when "wgx" or "wgxpath" will do?
    "*": {
      "wgx": "wicked-good-xpath",
      "wgxpath": "wicked-good-xpath"
    }
  }
})

// ...elsewhere...
require(["wgx"], function(wgx) {
  wgx.install(someOtherWindow)
  doStuffWith(someOtherWindow)
})

// ...elsewhere...
define(["actualDependency", "wgxpath"], function(actualDependency) {
  return function useActualDependencyOnCertainElements(xpath) {
    var xpathResult = document.evaluate(xpath, document, etc. etc.)
    var elements = ...convert xpathResult to array...
    actualDependency.useElements(elements)
  }
})
```

**Comment by vitrilo** [comment] 2016-05-11 10:23
I'm still failing to use library under IE11. The library seems don't search enything under IE 11. On FF and Chrome all works okay.

```javascript
wgxpath.install();
var src = '<?xml version="1.0" encoding="utf-8" ?><Root><Menu ID="11"></Menu></Root>';
var parser = new DOMParser();
var xml = parser.parseFromString(src, "application/xml");
wgxpath.install({'document':xml});
var result = xml.evaluate("//Menu", xml, null, XPathResult.ANY_TYPE, null);
console.log(result.iterateNext())
```
The line "wgxpath.install({'document':xml});" just allow to search only //Root node, but not child.

What am I doing wrong?

**Comment by ScottFreeCode** [comment] 2016-05-11 23:27
- `wgxpath.install({document: xml})` is no longer needed.
- This seems to be a problem with the `descendant` axis (in XML):
  - [ ] `//Root`
  - [ ] `//Menu`
  - [ ] `/descendant::Root`
  - [ ] `/descendant::Menu`
  - [ ] `/descendant-or-self::Root`
  - [ ] `/descendant-or-self::Menu`
  - [x] `//self::Root`
  - [x] `//self::Menu`
  - [x] `//*[self::Root]`
  - [x] `//*[self::Menu]`
  - [ ] `/Root//Root` -- wouldn't work anyway
  - [ ] `/Root//Menu`
  - [ ] `/Root/descendant::Root` -- wouldn't work anyway
  - [ ] `/Root/descendant::Menu`
  - [x] `/Root/descendant-or-self::Root`
  - [ ] `/Root/descendant-or-self::Menu`
  - [x] `/Root//self::Root`
  - [x] `/Root//self::Menu`
  - [ ] `/Root//*[self::Root]` -- wouldn't work anyway
  - [x] `/Root//*[self::Menu]`
- I used `wgxpath.install(window, true)` to force use of WGXPath on Firefox and got the same results, so it's not IE-specific (by default WGX doesn't override the browser's built-in XPath implementation, so that would be why you didn't have the problem on Firefox).

(List generated by this code in case anyone wants to clean it up and make some kind of test out of it or tinker with it and see if anything else affects whether it works:)
```js
wgxpath.install(window, true)
var src = '<?xml version="1.0" encoding="utf-8" ?><!DOCTYPE Root><Root><Menu ID="11"></Menu></Root>'
var xml = new DOMParser().parseFromString(src, "application/xml")
var prefixes = ["//", "/descendant::", "/descendant-or-self::", "//self::", "//*[self::"]
prefixes = prefixes.concat(prefixes.map(function(prefix) {
  return "/Root" + prefix
}))
prefixes.forEach(function(prefix) {
  ["Root", "Menu"].forEach(function(tag) {
    var result = xml.evaluate(prefix + tag + (/[[]/.test(prefix)?"]":""), xml, xml.createNSResolver(xml), XPathResult.ANY_TYPE, null)
    document.write("- [" + (result.iterateNext()?"x":" ") + "] `" + prefix + tag + (/[[]/.test(prefix)?"]":"") + "`<br />")
  })
})
```

**Comment by vitrilo** [comment] 2016-05-12 10:24
@ScottFreeCode,@Dominator008 Big thanks for explanation!

> This seems to be a problem with the descendant axis

I'am guess it this is a reason to reopen this bug, because XMLDocument not fully supported, and as we uncovered its unrelated to IE, right?
Or create a separate bug like "XMLDocument descendant axis issue"?

**Comment by bedney** [comment] 2016-05-12 12:38
Let's not reopen this bug.

@ScottFreeCode can you open a separate bug having to do with descendant axis issues?

Thanks!
